name: Deploy test
on:
  workflow_dispatch:

jobs:
  build-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install modules
        run: yarn --immutable
      - name: Build code
        run: yarn build
      - name: List dist contents
        run: ls -la dist/