name: Build and lint code

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened]
  workflow_dispatch:

jobs:
  build-and-lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install modules
        run: yarn --immutable
      - name: Build code
        run: yarn build
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci .